import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { NextLink } from '@mantine/next';
import { Button, Container } from '@mantine/core';
import PostContent, { PostProps } from '../../components/PostContent';

type Props = {
  post: PostProps
}

const Post: NextPage<Props> = (props: Props) => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostContent {...props.post}></PostContent>
    </Container>
  );
};

export const getServerSideProps: GetServerSideProps = async ({params}) => {
  const res = await fetch(`http://localhost:3000/api/posts/${params.id}`);
  const post = await res.json();
  return {
    props: { post },
  };
};

export default Post;
