import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { NextLink } from '@mantine/next';
import { Button, Container } from '@mantine/core';
import Post, { PostProps } from '../components/Post';

type Props = {
  posts: PostProps[]
}

const Home: NextPage<Props> = (props: Props) => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>マイブログ</h1>
      {props.posts.map(({ id, title, created_at }) => (
        <div key={id}>
          <Post id={id} title={title} created_at={created_at}></Post>
        </div>
      ))}
    </Container>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/posts?searchString=');
  const posts = await res.json();
  return {
    props: { posts },
  };
};

export default Home;
