import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { NextLink } from '@mantine/next';
import { Button, Container } from '@mantine/core';
import Post, { PostProps } from '../components/Post';
import React, { useState } from 'react';
// import Layout from '../components/Layout';
import Router from 'next/router';
import { useForm } from '@mantine/form';
import { NumberInput, TextInput, Button } from '@mantine/core';

type Inputs = {
  example: string;
  exampleRequired: string;
};

const New: NextPage<Props> = (props: Props) => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>マイブログ</h1>
      <form action="/send-data-here" method="post">
        <label htmlFor="roll">Roll Number</label>
        <input
          type="text"
          id="roll"
          name="roll"
          required
          minLength={10}
          maxLength={20}
        />
        <label htmlFor="name">Name:</label>
        <input type="text" id="name" name="name" required />
        <button type="submit">Submit</button>
      </form>
    </Container>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/posts?searchString=');
  const posts = await res.json();
  return {
    props: { posts },
  };
};

export default New;
